Matataki-io/Matataki-FE

components/follow_btn/index.vue, components/footer/index.vue, pages/agreement.vue, pages/policy.vue
1. 修复 取关按钮 UI 显示错误
2. 移除 隐藏用户协议和隐私协议
=> 取关按钮 UI 显示错误 & 隐藏用户协议和隐私协议

components/user/user_nav.vue, pages/_lang/setting/account.vue, plugins/router.js
=> 🚀 账号绑定完善流程

app.html, components/article/article_ipfs.vue, pages/_lang/ipfs/_hash.vue, pages/_lang/p/_id.vue
=> 🔧修复ipfs地址展示问题 测试百度统计 

components/header/index.vue, components/modal/QRCodeDialog.vue, utils/request.js
拦截401, 弹出登录框,  修复pc端文章分享无限二维码bug ,🔧 修复弹出解绑密码框, 搜索框也会填充的问题
=> 拦截401, 弹出登录框,  修复pc端文章分享无限二维码bug ,🔧 修复弹出解绑密码框, 搜索框也会填充的问题

components/button_load_more/index.vue, components/header/index.vue, components/home_layout/index.vue, components/ring_layout/index.vue, pages/_lang/ring/_id.vue, pages/ring/_id.vue
=> fan票圈详情文章页面

components/Auth/login.vue, pages/_lang/login/github.vue, pages/_lang/setting/account.vue
=> github 绑定登录优化

components/buy_card/index.vue, components/holdliquidity_detail/index.vue, components/tokens_detail/index.vue, components/user/user_nav.vue, pages/_lang/buy/index.vue, pages/_lang/minetoken/index.vue
1. 我的票夹中展开的明细记录页码被错误同步了
2. 消费记录页面缺少一个标题
=> 修了一些BUG，详见描述

components/article/UserInfoHeader.vue, components/comment/Card.vue, components/comment/article_card.vue, components/my_account/my_account_nav.vue, components/share_card/index.vue, components/share_inside_card/index.vue, components/share_p_card/index.vue, components/share_page/share_header.vue, components/user/user_page_nav.vue, locale/en.js, locale/zh.js, pages/_lang/setting/index.vue, pages/_lang/user/_id/share/index.vue, pages/user/_id/share.vue, store/user.js
1. 新增个人主页-分享
2. 修改部分跳转在新标签页打开
3. 修复个人主页显示错误的bug
=> 新增个人主页-分享、修改部分跳转在新标签页打开、修复个人主页显示错误的bug

components/modal/QRCodeDialog.vue, components/modal/Share.vue, components/token/token_layout.vue, components/user/edit_minetoken.vue, components/user/fan_coins_manage_layout.vue, pages/_lang/tokens/apply.vue
=> 优化文章分享为图片后的样式  fan票发布文字说明和细节调整

components/token/my_token_header.vue, pages/_lang/token/index.vue
=> Fan票列表增加了显示自己Fan票的页头

app.html, pages/_lang/home/index.vue, utils/load_script.js
=> 动态加载script, 离开页面销毁事件

components/token/token_layout.vue, pages/_lang/token/_id.vue
=> Fan票详情页预渲染

pages/_lang/tokens/index.vue
=> 转赠功能增加全部按钮

components/token/token_buy_card.vue
=> 修复快捷购买订单创建失败问题

locale/en.js, nuxt.config.js, package.json, utils/creative_commons.js, yarn.lock
删了twitter_login.js后忘记在nuxt里把引用删掉了……
=> fix nuxt impot bug.

components/Auth/login.vue, pages/_lang/setting/account.vue
=> 隐藏twitter login and bind

components/become_an_article_editor/index.vue, pages/_lang/p/_id.vue, pages/_lang/publish/_type/_id.vue
对应的Issues：https://github.com/Matataki-io/Matataki-FE/issues/197
=> 文章编辑权限的UI，包括发文页面和文章展示页面（暂无实际功能）

package.json
=> 更新mavon-editor-matataki的版本

components/notification/objectCard.vue
=> 消息页面用户卡片的css使用兼容性更好的写法

components/Auth/login.vue
https://github.com/Matataki-io/Matataki-FE/issues/535
=> 给登录按钮设定 submit type

pages/user/_id/info/index.vue
Disable opener of user website
<details>
<summary>POC</summary>
</details>
=> Fix potential security risks

components/token/token_layout.vue, components/token_banner.vue, components/user/user_page.vue, pages/login/twitter/callback.vue, plugins/vue_plugins.js
- Check login status before transfer on user page
- Fix Fan Ticket link
- Fix eslint warn
- Other minor changes...
=> Check before transfer

components/bannerUpload/index.vue, components/imgUpload/index.vue, components/img_upload/index.vue
=> 修复图片上传失败时显示的错误 i18n 内容

components/Auth/index.vue, pages/login/oauth/_redirect.vue
=> feat: 添加了登陆自动跳转的页面

layouts/empty.vue, pages/publish/_type/_id.vue
1. empty layout 刷新没有 currentUserInfo bug
2. 重编辑不显示token & 无法重新发布并提示“请选择支付类型”
3. 文章设置支付任意CNY可见发布出来都是1CNY
=> 🚑 hotfixed: emergency release

pages/login/oauth/_redirect.vue
=> fix: 修复了登录回跳页面的一些问题和控制

common/components/avatar/index.vue, components/token/token_buy_card2.vue
=> hotfix: v4.6.2

common/components/avatar/index.vue, components/article/UserInfoHeader.vue, components/token/token_buy_card2.vue
=> hotfix v4.6.2

components/draft_artifcle_card_mini/index.vue, pages/preview/_id.vue, pages/user/_id/draft/index.vue
- 定时发布的草稿增加了“取消发布”按钮
- 点击定时发布状态的草稿卡片自动创建并打开草稿预览
- 草稿预览中展示定时发布时间信息
=> 定时发布的草稿增加了“取消发布”按钮；点击定时发布状态的草稿打开草稿预览；草稿预览中展示定时发布时间信息。

env.js
=> 🐛 fix: 修复 env 地址错误

pages/setting/account.vue
=> ✨ 适配 Matataki Auth 后端系统 

pages/setting/account.vue
=> 🔥 Removed useless code

pages/setting/account.vue
=> feat: 取消指定更新，设置为全局刷新

pages/setting/account.vue
=> feat: 修复文本问题

pages/timeline/index.vue
https://github.com/Matataki-io/Matataki-FE/issues/973
=> timeline 在移动端比例下支持筛选器和作者列表的展示

nuxt.config.js
=> feat: split element

pages/publish/_type/_id.vue
=> feat: 发布文章自动写入默认标题

components/header/index.vue
修复在Header的特定区域点击会进入"写文章"页面的问题，适配在窄屏幕下的"写文章"按钮边框
=> 修复Issue # 1096中发现的问题

components/feedback/index.vue, components/footer/index.vue, components/liquidity_total_transaction_flow_card.vue, components/token/navigation_bar.vue, layouts/default.vue, pages/token/index.vue
=> footer移动端样式优化

components/token_card/index.vue, components/token_list.vue
=> Fan票列表样式优化

components/p_page/sidebar.vue
=> 修复移动端文章阅读页面Footer被遮挡的问题

pages/p/_id.vue
close #1151 
有文章 Tags 的情况
无文章 Tags 的情况
=> feat: article tags to meta keywords

locale/en.json, locale/zh.json, pages/publish/_type/_id.vue
=> 编辑文章时也会显示是否发布到 GitHub 但是不可修改

pages/publish/_type/_id.vue, pages/setting/index.vue
=> 修复hcaptcha的语言显示问题

pages/login/github.vue
=> 减少GitHub登录时请求的权限范围

pages/publish/_type/_id.vue
=> 发文失败后重置 hCaptcha 状态，编辑文章提交时加入 ipfs_or_github 参数

common/components/ipfs_all/index.vue, pages/p/_id.vue
=> 将 GitHub 上发布的文章 Hash 替换成 JSON 文件的 Hash

common/components/ipfs_all/index.vue, components/article/UserInfoHeader.vue
=> 修复主账号不是 GitHub 时发布在 GitHub 上的文章无法正确显示用户名的问题

config/iframe-whitelist.json
=> 为 iframe-whitelist.json 加上逗号

locale/zh.json, pages/setting/indieblog.vue
=> 创建独立子站前判断 GitHub 绑定状态

pages/setting/indieblog.vue
=> 独立子站设置页面: 更换时间下拉列表的值

api/API.js, locale/en.json, locale/zh.json, pages/setting/indieblog.vue
=> 独立子站: 新增部署状态提示

locale/en.json, locale/zh.json, pages/publish/_type/_id.vue
=> 文章发布: 显示发布选项时判断是否已经创建独立子站，修改发布选项的提示信息

pages/setting/system.vue
=> 用户设置: 为「接受他人文章权限移交」项目加上 hCaptcha

locale/zh.json, pages/setting/indieblog.vue
=> 独立子站设置: 将创建步骤中的「保存仓库名并创建子站」步骤拆分为「保存仓库名」和「创建子站」两个步骤

components/user/user_page.vue, locale/zh.json
=> 用户详情页: 将子站链接浓缩成一个按钮

common/components/ipfs_all/index.vue, components/article/UserInfoHeader.vue, locale/zh.json, pages/setting/indieblog.vue, yarn.lock
=> 文章内容页: 更换文章存储位置链接

api/API.js, locale/zh.json, pages/setting/indieblog.vue
=> 独立子站设置: 对齐后端进行的优化

api/API.js, locale/zh.json, pages/setting/indieblog.vue
=> 独立子站设置: 修改主题功能前端已对接

components/indie-blog-creation/index.vue, components/indie-blog-settings/index.vue, middleware/redirect.js, pages/setting/indieblog.less, pages/setting/indieblog.vue
=> 独立子站: 分离创建子站和子站设置的业务代码

common/components/ipfs_all/index.vue, components/article/UserInfoHeader.vue
I will revert this commit if it doesn't, or it's fine though.
=> Testing does <client-only> tag fix the last problem or not

components/indie-blog-settings/index.vue, locale/zh.json
=> fix: try to fix chinese language when theme is cake
